[v1]
"gitui 0.27.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitui"]
"jnv 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["jnv"]
"starship 1.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
